packages:
  - 'frontend'
  - 'auth'
  - 'smh-manager'
  - 'meter-manager/create-meter-service'
  - 'meter-manager/delete-meter-service'
  - 'meter-manager/get-meter-service'
  - 'meter-manager/update-meter-service'
  - 'smh-manager/create-hub-service'
  - 'smh-manager/delete-hub-service'
  - 'smh-manager/get-hub-service'
  - 'smh-manager/update-hub-service'
  - 'user-management/set-all-meters-by-hub-id-service'
  - 'user-management/set-meter-by-id-service'
  - 'user-management/set-hub-status-service'
  - 'meter-setter/create-config'
  - 'meter-setter/delete-config'
  - 'meter-setter/get-config'
  - 'meter-setter/update-config'
  
